"""remove_customer_model

Revision ID: 782446777869
Revises: c7779b8d75ec
Create Date: 2026-01-18 10:32:23.233840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '782446777869'
down_revision = 'c7779b8d75ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))

    # Now drop customers table
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_trader_id', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'customer_email')
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trader_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], name='customers_trader_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    sa.UniqueConstraint('trader_id', 'email', name='customers_trader_id_email_key')
    )
    op.create_index('ix_customers_trader_id', 'customers', ['trader_id'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    # ### end Alembic commands ###
