"""add_accepted_cancelled_order_status

Revision ID: c0402fe77407
Revises: e158fbf5061b
Create Date: 2026-02-05 11:39:37.668061

"""
from alembic import op
import sqlalchemy as sa


revision = 'c0402fe77407'
down_revision = 'e158fbf5061b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add new enum values for OrderStatus
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'ACCEPTED'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'CANCELLED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_customers_email'), 'shop_customers', ['email'], unique=True)
    op.create_index(op.f('ix_shop_customers_id'), 'shop_customers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_customers_id'), table_name='shop_customers')
    op.drop_index(op.f('ix_shop_customers_email'), table_name='shop_customers')
    op.drop_table('shop_customers')
    # ### end Alembic commands ###
