"""Add cart_items table

Revision ID: e158fbf5061b
Revises: 782446777869
Create Date: 2026-01-22 15:30:10.641343

"""
from alembic import op
import sqlalchemy as sa


revision = 'e158fbf5061b'
down_revision = '782446777869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('product_source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'product_source_id', name='_trader_product_uc')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_source_id'), 'cart_items', ['product_source_id'], unique=False)
    op.create_index(op.f('ix_cart_items_trader_id'), 'cart_items', ['trader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_trader_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_product_source_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
